"""initial schema

Revision ID: 02ba0896868b
Revises: 
Create Date: 2026-08-24 23:33:29.608495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '02ba0896868b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('notion_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('app_user_id', sa.UUID(), nullable=False),
    sa.Column('notion_workspace_id', sa.Text(), nullable=False),
    sa.Column('workspace_name', sa.Text(), nullable=True),
    sa.Column('workspace_icon', sa.Text(), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('last_synced_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['app_user_id'], ['app_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_user_id', 'notion_workspace_id', name='uq_connection_user_workspace')
    )
    op.create_table('notion_pages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.Column('notion_page_id', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('last_edited_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['notion_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connection_id', 'notion_page_id', name='uq_page_connection_page')
    )
    op.create_table('notion_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('page_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=2048), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['notion_pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('page_id', 'chunk_index', name='uq_chunk_page_index')
    )
    # ### end Alembic commands ###

    # Postgres does not auto-index FK columns; add them explicitly for join/lookup performance.
    op.create_index('ix_notion_connections_app_user_id', 'notion_connections', ['app_user_id'])
    op.create_index('ix_notion_pages_connection_id', 'notion_pages', ['connection_id'])
    op.create_index('ix_notion_pages_last_edited_time', 'notion_pages', ['last_edited_time'])
    op.create_index('ix_notion_chunks_page_id', 'notion_chunks', ['page_id'])

    # Baseline ANN index for similarity search. pgvector's ivfflat/hnsw indexes cap out at
    # 2000 dimensions for full-precision `vector`, but our embeddings are 2048-d, so we index
    # a half-precision expression instead (pgvector's documented workaround for >2000 dims).
    op.execute(
        "CREATE INDEX ix_notion_chunks_embedding_cosine ON notion_chunks "
        "USING hnsw ((embedding::halfvec(2048)) halfvec_cosine_ops)"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP INDEX IF EXISTS ix_notion_chunks_embedding_cosine")
    op.drop_index('ix_notion_chunks_page_id', table_name='notion_chunks')
    op.drop_index('ix_notion_pages_last_edited_time', table_name='notion_pages')
    op.drop_index('ix_notion_pages_connection_id', table_name='notion_pages')
    op.drop_index('ix_notion_connections_app_user_id', table_name='notion_connections')

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notion_chunks')
    op.drop_table('notion_pages')
    op.drop_table('notion_connections')
    op.drop_table('app_users')
    # ### end Alembic commands ###
